spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=g130restapipractice
    username: kuatabylay
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true